### ISSUE TITLE
Need to change the template, in fact, need to rethink what we do

### ISSUE THREAD

**Issue by romanchyla** [adsabs/adsabs-webservices-blueprint#8]
I'd like to say that this implementation poses challenges to any potential adopter and this point can be illustrated by one implementation of the export services

this is how the app should look like IMO:

```
blueprint = Blueprint('foo')
@route(blueprint, '/foo', methods=['GET'])
@ads_scope('some', 'foo', 'bar')
@rate_limit(6000)
def foo():
    return requests.post(URL, request.args), 200
```

This is how it looks now:

```
#This resource must be available for every adsabs webservice.
class Resources(Resource):
  '''Overview of available resources'''
  scopes = []
  rate_limit = [1000,60*60*24]
  def get(self):
    func_list = {}

    clsmembers = [i[1] for i in inspect.getmembers(sys.modules[__name__], inspect.isclass)]
    for rule in current_app.url_map.iter_rules():
      f = current_app.view_functions[rule.endpoint]
      #If we load this webservice as a module, we can't guarantee that current_app only has these views
      if not hasattr(f,'view_class') or f.view_class not in clsmembers:
        continue
      methods = f.view_class.methods
      scopes = f.view_class.scopes
      rate_limit = f.view_class.rate_limit
      description = f.view_class.__doc__
      func_list[rule.rule] = {'methods':methods,'scopes': scopes,'description': description,'rate_limit':rate_limit}
    return func_list, 200



class Export(Resource):
  '''Returns export data for a list of bibcodes'''
  scopes = ['api:search'] 
  rate_limit = [1000,60*60*24]

  def post(self):
        .....

```

we should write a wrapper that will explore the app blueprint (python duck typing) and export them in the form of a catalog (as restful classes, if you insist that should be used), and this will be exposed to the aws application, but that should be completely hidden - and we should check there the return types!

The export service, for example, works standalone, but for some reason it doesn't play with the API - I suspect it is because the specification does not say whether the return value should be a string or a dictionary, in fact I see that sometimes it returns string, and sometimes a dictionary.

**Comment by vsudilov** [comment]
closed 0432eb5d9383c0f0b9db457728413a4b0216182e
